version: 0.2

env:
  shell: bash
  # Secrets Manager - AWS CodeBuild will automatically inject these
  # The secret name is passed from Terraform via GITHUB_TOKEN_SECRET_NAME variable
  secrets-manager:
    GITHUB_TOKEN: $GITHUB_TOKEN_SECRET_NAME

phases:
  pre_build:
    on-failure: ABORT
    commands:
      - echo "Start pre build phase"
      # Extract metadata from Lambda trigger
      - export REPO_NAME=$(jq -r '.repo_name' metadata.json)
      - export BRANCH_NAME=$(jq -r '.branch_name' metadata.json)
      - export COMMIT_HASH=$(jq -r '.commit_id' metadata.json)
      - echo "GITHUB_TOKEN is set"
      # Clone the repository
      - mkdir working_dir && cd working_dir
      - git clone https://oauth2:$GITHUB_TOKEN@github.com/$REPO_NAME .
      - git checkout $BRANCH_NAME
      # Login to Amazon ECR
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ACCOUNTID.dkr.ecr.$AWS_REGION.amazonaws.com
      # Set image tag to commit hash
      - export IMAGE_TAG=$COMMIT_HASH
      - export REPOSITORY_URI=$ACCOUNTID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME
      - echo "REPOSITORY_URI:" $REPOSITORY_URI

  build:
    commands:
      - ls -la
      - docker build -f Dockerfile . -t $REPOSITORY_URI:$IMAGE_TAG
      - echo "Build started on" $(date) "at commitID:" $COMMIT_HASH
      - echo "Adding ENV, config... IMAGE_TAG:" $IMAGE_TAG
      - echo "Building the Docker image..." $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo "Build completed on" $(date)
      - echo "Pushing to repo"
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "Promote image tag to latest"
      - docker tag $REPOSITORY_URI:$IMAGE_TAG $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:latest
      - echo "Writing image definitions file with IMAGE_TAG:" $IMAGE_TAG
      - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER $REPOSITORY_URI:$IMAGE_TAG > artifact.json
      - ls -la
      - cat artifact.json

artifacts:
  name: artifacts
  files:
    - 'working_dir/artifact.json'
